### ISSUE TITLE
[CNAMERecord]: expected a value of "CnameRecord" or Null

### ISSUE THREAD

**Issue by Luuk-Axians** [Azure/bicep-types-az#1391] opened 2023-03-03 11:52 UTC
### Resource Type

Microsoft.Network/dnsZones/CNAME

### Api Version

2018-05-01

### Issue Type

Type is unavailable

### Other Notes

We can't use the CNAMERecords Bicep as it gives an error within Visual Studio Code and when we deploy the pipeline it gives that same error. It looks like because of this error the value will stay Null instead of take the parameter set in the JSON file. Anyone any idea what i'm missing?

**Error**
The property "CNAMERecord" expected a value of type "CnameRecord | null" but the provided value is of type "[object]". If this is an inaccuracy in the documentation, please report it to the Bicep Team.

**JSON Parameter file**
```json
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "recordDetails": {
            "value": [
                {
                    "dnszTTL": "3600",
                    "dnszName": "thompsonmaat.com",
                    "dnszCnameRecord": "www",
                    "dnszCnameTarget": "cna"
                }
            ]
        }
    }
}
```

### Bicep Repro
```bicep
@description('RecordDetails is needed so multiple records are possible')
param recordDetails array 

resource dnszCnameRecord 'Microsoft.Network/dnsZones/CNAME@2018-05-01' = [for recordDetail in recordDetails : {
  name: '${recordDetail.dnszName}/${recordDetail.dnszCnameRecord}'
    properties: {
      TTL: recordDetail.dnszTTL
      CNAMERecord: [
      {
        cname: recordDetail.dnszCnameTarget
      }
    ]
}
}]

output dnszCNResourceId array = [for record in range(0, length(recordDetails)): {
  'resourceid${record}': dnszCnameRecord[record].id
}]
```
### Confirm

- [X] I have searched this repository and have not found similar issue reports.

**Comment by anthony-c-martin** [comment] 2023-03-03 11:57
@Luuk-Axians I think you just need the following to fix it - rather than wrapping the object in an array:
```bicep
@description('RecordDetails is needed so multiple records are possible')
param recordDetails array

resource dnszCnameRecord 'Microsoft.Network/dnsZones/CNAME@2018-05-01' = [for recordDetail in recordDetails: {
  name: '${recordDetail.dnszName}/${recordDetail.dnszCnameRecord}'
  properties: {
    TTL: recordDetail.dnszTTL
    CNAMERecord: {
      cname: recordDetail.dnszCnameTarget
    }
  }
}]

output dnszCNResourceId array = [for record in range(0, length(recordDetails)): {
  'resourceid${record}': dnszCnameRecord[record].id
}]
```

**Comment by Luuk-Axians** [comment] 2023-03-03 12:10
Wow i feel silly, thanks for this it works now!

**Comment by anthony-c-martin** [comment] 2023-03-03 18:13
> Wow i feel silly, thanks for this it works now!

@Luuk-Axians don't feel silly - it's our responsibility to make Bicep intuitive.

If you don't mind sharing, I'd be interested to understand if there's anything you feel that would have made this clearer, such that you'd have been able to understand the problem without having to raise an issue. (e.g. the wording of the error message, where it appeared, anything else...)

**Comment by anthony-c-martin** [comment] 2023-03-06 12:22
Closing this issue as the problem is resolved, but feel free to comment here or raise a new issue if you've got an answer to the above.

**Closed by anthony-c-martin** 2023-03-06 12:22 UTC
Labels: inaccuracy, Needs: Triage :mag:

**Comment by Luuk-Axians** [comment] 2023-03-06 12:58
@anthony-c-martin After re reading the error it does sort of make sense, [object] should have given it away probably. So i dont have any ideas how to make it more clear from the error message. Unless it makes sense to point out that it got an array and was expecting another type? 

But i'm no programmer so it might make perfect sense for those that are experienced in programming languages ;)

thanks gain.
