### ISSUE TITLE
[Microsoft.App/containerApps]: invalid cpu type

### ISSUE THREAD

**Issue by kynrai** [Azure/bicep-types-az#1924] opened 2023-10-27 18:58 UTC
### Resource Type

Microsoft.App/containerApps

### Api Version

2023-05-01

### Issue Type

Inaccurate property type(s)

### Other Notes

cpu value expects int | null but should require a string

```json 
{
  "code": "ContainerAppInvalidResourceTotal", 
  "message": "The total requested CPU and memory resources for this application (CPU: 1, memory: 1.0) is invalid. Total CPU and memory for all containers defined in a Container App must add up to one of the following CPU - Memory combinations: [cpu: 0.25, memory: 0.5Gi]; [cpu: 0.5, memory: 1.0Gi]; [cpu: 0.75, memory: 1.5Gi]; [cpu: 1.0, memory: 2.0Gi]; [cpu: 1.25, memory: 2.5Gi]; [cpu: 1.5, memory: 3.0Gi]; [cpu: 1.75, memory: 3.5Gi]; [cpu: 2.0, memory: 4.0Gi]"
}
```

### Bicep Repro

```bicep
resource directory 'Microsoft.App/containerApps@2023-05-01' = {
  name: 'directory'
  location: location
  properties: {
    environmentId: environment.id
    configuration: {
      ingress: {
        external: true
        targetPort: 80
      }
    }
    template: {
      containers: [
        {
          image: 'nginx'
          name: 'directory-server'
          resources: {
            cpu: '0.5'
            memory: '1.0Gi'
          }
        }
      ]
    }
  }
}
```

### Confirm

- [X] I have read the troubleshooting guide and looked for duplicates.

**Comment by carlin-q-scott** [comment] 2023-12-20 23:01
duplicate of #1848

**Comment by stephaniezyen** [comment] 2024-02-21 17:14
Closing as duplicate ^

**Closed by stephaniezyen** 2024-02-21 17:14 UTC
Labels: inaccuracy, Service Attention, ContainerApp
