### ISSUE TITLE
Microsoft.App/containerApps: Container CPU only accepts Int | null

### ISSUE THREAD

**Issue by vitorlinares** [Azure/bicep-types-az#1930] opened 2023-11-02 18:57 UTC
### Resource Type

Microsoft.App/containerApps

### Api Version

2023-05-01

### Issue Type

Inaccurate property type(s)

### Bicep Repro

resource aceApp 'Microsoft.App/containerApps@2023-05-01' = {
  name: appName
  location: location  
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    workloadProfileName: 'Consumption'
    managedEnvironmentId:environmentId
    configuration:{
      secrets:[
        {
          name:'appconfig'
          value:appConfig.listKeys().value[0].connectionString
        }
      ]
      ingress:{
        clientCertificateMode:'ignore'
        allowInsecure:false
        external:true
        stickySessions:{
          affinity:'sticky'
        }
        targetPort:80
        transport:'auto'        
      }
      activeRevisionsMode:'Single'      
    }
    template:{
      scale:{
        minReplicas:1
        maxReplicas:1
      }
      containers:[
        {
          name: toLower('${appName}-sample-container')
          image:'mcr.microsoft.com/k8se/quickstart:latest'
          resources:{
            cpu:'0.5'
            memory:'1.0Gi'
          }
          env:[
            {
              name:'AppConfig'
              value:'secretref=appconfig'
            }
          ]
        }
      ]
    }
  }
}

### Confirm

- [X] I have read the troubleshooting guide and looked for duplicates.

**Comment by carlin-q-scott** [comment] 2023-12-20 23:00
duplicate of #1924

**Comment by stephaniezyen** [comment] 2024-02-21 17:13
Closing as a duplicate of ^

**Closed by stephaniezyen** 2024-02-21 17:13 UTC
Labels: inaccuracy
