### ISSUE TITLE
[Microsoft.Web/connections]: The property "kind" does not exist in the resource or type definition

### ISSUE THREAD

**Issue by ayoussef-insight** [Azure/bicep-types-az#1352] opened 2023-02-14 01:38 UTC
### Resource Type

Microsoft.Web/connection

### Api Version

016-06-01

### Issue Type

Missing property(s)

### Other Notes

kind property is missing from Microsoft.Web/connections@2016-06-01

### Confirm

- [X] I have searched this repository and have not found similar issue reports.

**Comment by stephaniezyen** [comment] 2023-04-18 19:02
Duplicate of #1501

**Closed by stephaniezyen** 2023-04-18 19:02 UTC
Labels: inaccuracy, RP: Microsoft.Web
