### ISSUE TITLE
Conflicts when trying to instanciate multiple child resources with loop

### ISSUE THREAD

**Issue by sinedied** [Azure/bicep-types-az#1736] opened 2023-07-24 08:20 UTC
**Bicep version**
Bicep CLI version 0.19.5 (87ca110fc0)

**Describe the bug**
I'm trying to create an Azure Open AI with 2 child deployments using a for loop, and I get a conflict error:
```
ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/7944cce1-9fc2-4583-a3a2-8211a625ea06/resourceGroups/rg-moaw2-prod/providers/Microsoft.Resources/deployments/deployment-moaw2-prod-westeurope","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"ResourceDeploymentFailure","target":"/subscriptions/7944cce1-9fc2-4583-a3a2-8211a625ea06/resourceGroups/rg-moaw2-prod/providers/Microsoft.Resources/deployments/openai","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.","details":[{"code":"DeploymentFailed","target":"/subscriptions/7944cce1-9fc2-4583-a3a2-8211a625ea06/resourceGroups/rg-moaw2-prod/providers/Microsoft.Resources/deployments/openai","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"RequestConflict","message":"Another operation is being performed on the parent resource '/subscriptions/7944cce1-9fc2-4583-a3a2-8211a625ea06/resourceGroups/rg-moaw2-prod/providers/Microsoft.CognitiveServices/accounts/oai-moaw2-prod-xat3r7csb2dra'. Please try again later."}]}]}]}}
```

**To Reproduce**
Here's the related Bicep code to reproduce it:

```Bicep

resource openAi 'Microsoft.CognitiveServices/accounts@2023-05-01' = {
  name: 'oai-${projectName}-${environment}-${uid}'
  location: location
  tags: tags
  sku: {
    name: 'S0'
  }
  kind: 'OpenAI'
  properties: {
    customSubDomainName: uniqueString(uid, 'OpenAI')
    publicNetworkAccess: 'Enabled'
  }
}

resource models 'Microsoft.CognitiveServices/accounts/deployments@2023-05-01' = [for model in modelsConfig: {
  parent: openAi
  name: model.name
  sku: {
    name: 'Standard'
    capacity: contains(model, 'capacity') ? model.capacity : 33
  }
  properties: {
    model: {
      format: 'OpenAI'
      name: model.name
      version: model.version
    }
    versionUpgradeOption: 'OnceNewDefaultVersionAvailable'
    raiPolicyName: 'Microsoft.Default'
  }
}]

```

**Additional context**
Running the same deployment multiple times eventually succeeds, I suspect when the child resources have all been created.

It seems to me that the child resources (OpenAI deployments) should not be run in parallel but sequentially, though it doesn't seem to respect ARM base principles and I'm not sure how it could be achieved with a loop.

**Comment by sinedied** [comment] 2023-08-04 08:31
I created an Azure support ticket, and I'm trying to find out the relevant team to report this issue to.

**Comment by FreBon** [comment] 2023-10-17 17:22
Same issue here, did you get any responses from the suport?

**Comment by anthony-c-martin** [comment] 2023-10-18 03:35
> It seems to me that the child resources (OpenAI deployments) should not be run in parallel but sequentially, though it doesn't seem to respect ARM base principles and I'm not sure how it could be achieved with a loop.

Agree with the consensus that this seems to be a Resource Provider bug, but wanted to offer a possible workaround - [batchSize](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/loops#deploy-in-batches) set to 1 will run a loop sequentially:

```bicep
@batchSize(1)
resource models 'Microsoft.CognitiveServices/accounts/deployments@2023-05-01' = [for model in modelsConfig: {
...
```

**Comment by sinedied** [comment] 2023-10-23 06:55
Support went back and forth with the service team, and they replied that this is intended behavior and they do not plan to change/fix the current behavior for now.

The solution is to use @anthony-c-martin 's approach setting `batchSize` to 1.

**Comment by stephaniezyen** [comment] 2023-11-14 20:00
Closing as service team had mentioned this as intended behavior. Please use the solution listed above

**Closed by stephaniezyen** 2023-11-14 20:00 UTC
Labels: Needs: Triage :mag:
