### ISSUE TITLE
Microsoft.MachineLearningServices workspaces/computes: missing properties

### ISSUE THREAD

**Issue by tfitzmac** [Azure/bicep-types-az#954] opened 2022-07-12 22:09 UTC
### Resource Type

Microsoft.MachineLearningServices workspaces/computes

### Api Version

2022-02-01-preview

### Issue Type

Missing property(s)

### Other Notes

The objects that vary by ComputeType are missing properties. This issue doesn't exist in 2022-01-01-preview but is present in 2022-02-01-preview and 2022-05-01. 

For example, if you look at ComputeInstance in [2022-02-01-preview](https://github.com/Azure/bicep-types-az/blob/main/generated/machinelearningservices/microsoft.machinelearningservices/2022-01-01-preview/types.md#computeinstance), you see only ComputeType. However, if you Iook at [2022-01-01-preview](https://github.com/Azure/bicep-types-az/blob/main/generated/machinelearningservices/microsoft.machinelearningservices/2022-01-01-preview/types.md#computeinstance), you see a properties object.

If you look at the [REST API specification](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-02-01-preview/machineLearningServices.json), you see the properties are still present.

### Confirm

- [X] I have searched this repository and have not found similar issue reports.

**Comment by jeskew** [comment] 2022-08-08 14:00
The root cause for this is that the generator's discriminated union parser assumes a certain pattern in Swagger that Microsoft.MachineLearningServices is no longer following for ComputeType. 

Usually, a discriminated union will be expressed using a combination of inherited and inlined properties, with each branch of the union extending a common base type and defining its own properties inline. The parser has a boolean flag (`includeBaseProperties`) that controls whether inherited properties are included in the generated type, with the assumption being that this would exclude the common base type's properties while still capturing the branch-specific, inline properties. It looks like Microsoft.MachineLearningServices went from [inlining branch-specific properties in version `2022-01-01-preview`](https://github.com/Azure/azure-rest-api-specs/blob/7473936304533e6716fc4563401bf265dda4cb64/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-01-01-preview/machineLearningServices.json#L3596-L3605) to [inheriting them in `2022-02-01-preview`](https://github.com/Azure/azure-rest-api-specs/blob/7473936304533e6716fc4563401bf265dda4cb64/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-02-01-preview/machineLearningServices.json#L3682-L3684).

I believe this issue could be addressed by passing more specific information about *which* base properties to exclude to the parser, though I will need to do some investigation and testing to make sure that changes effects would be localized to issues like this.

**Closed** 2022-08-25 17:57 UTC
Labels: bug, inaccuracy
